version: '3'
services:
  wordpress:
    image: wordpress
    environment:
      - WORDPRESS_DB_PASSWORD=password
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
      - ./wp-content:/var/www/html/wp-content
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
